Typo on this long string, see https://travis-ci.org/SMPyBandits/SMPyBandits/builds/458516725
https://travis-ci.org/SMPyBandits/SMPyBandits/builds/458516725

Traceback (most recent call last):
  File "main.py", line 281, in <module>
    evaluation.plotRegrets(envId, savefig=savefig, semilogx=semilogx, semilogy=semilogy, loglog=loglog, normalizedRegret=True)  # XXX To save the figure
  File "/home/travis/build/SMPyBandits/SMPyBandits/SMPyBandits/Environment/Evaluator.py", line 592, in plotRegrets
    plt.ylabel(r"Normalized regret%s$\frac{R_t}{\log(t)} = \frac{t}{\log(t)} \mu^* - \frac{1}{\log(t)}\sum_{s=1}^{t}$ %s%s" % (r"$\sum_{k=1}^{%d} \mu_k\mathbb{E}_{%d}[T_k(t)]$" % ("\n", self.envs[envId].nbArms, self.repetitions) if moreAccurate else r"$\mathbb{E}_{%d}[r_s]$" % (self.repetitions), ylabel2))
TypeError: %d format: a number is required, not str
The command "N=10 T=1000 python main.py" exited with 1.